name: PR Sanity checks

on:
  push:
    branches: [ dev ]
  pull_request:
    branches:
      - dev


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Test things
        run: |
            npm ci    # This will make sure that package.json and package-lock.json are in sync
            npm test  # This will be unit tests